import type { Song, PaginatedResponse } from "./api"

export const mockTopSongs: Song[] = [
  {
    id: 1,
    title: "O Mineiro e o Italiano",
    artist: "Tião Carreiro & Pardinho",
    youtube_url: "https://www.youtube.com/watch?v=s9kVG2ZaTS4",
    youtube_id: "s9kVG2ZaTS4",
    thumbnail: "https://img.youtube.com/vi/s9kVG2ZaTS4/hqdefault.jpg",
    views: 5200000,
    status: "approved",
    formatted_views: "5.2M",
    created_at: "2024-01-01",
  },
  {
    id: 2,
    title: "Rei do Gado",
    artist: "Tião Carreiro & Pardinho",
    youtube_url: "https://www.youtube.com/watch?v=abc123",
    youtube_id: "abc123",
    thumbnail: "https://img.youtube.com/vi/abc123/hqdefault.jpg",
    views: 4800000,
    status: "approved",
    formatted_views: "4.8M",
    created_at: "2024-01-02",
  },
  {
    id: 3,
    title: "Pagode em Brasília",
    artist: "Tião Carreiro & Pardinho",
    youtube_url: "https://www.youtube.com/watch?v=def456",
    youtube_id: "def456",
    thumbnail: "https://img.youtube.com/vi/def456/hqdefault.jpg",
    views: 4200000,
    status: "approved",
    formatted_views: "4.2M",
    created_at: "2024-01-03",
  },
  {
    id: 4,
    title: "Modas de Viola",
    artist: "Tião Carreiro & Pardinho",
    youtube_url: "https://www.youtube.com/watch?v=ghi789",
    youtube_id: "ghi789",
    thumbnail: "https://img.youtube.com/vi/ghi789/hqdefault.jpg",
    views: 3900000,
    status: "approved",
    formatted_views: "3.9M",
    created_at: "2024-01-04",
  },
  {
    id: 5,
    title: "Chico Mineiro",
    artist: "Tião Carreiro & Pardinho",
    youtube_url: "https://www.youtube.com/watch?v=jkl012",
    youtube_id: "jkl012",
    thumbnail: "https://img.youtube.com/vi/jkl012/hqdefault.jpg",
    views: 3600000,
    status: "approved",
    formatted_views: "3.6M",
    created_at: "2024-01-05",
  },
]

export const mockRemainingSongs: PaginatedResponse<Song> = {
  data: [
    {
      id: 6,
      title: "Cabocla Teresa",
      artist: "Tião Carreiro & Pardinho",
      youtube_url: "https://www.youtube.com/watch?v=mno345",
      youtube_id: "mno345",
      thumbnail: "https://img.youtube.com/vi/mno345/hqdefault.jpg",
      views: 3200000,
      status: "approved",
      formatted_views: "3.2M",
      created_at: "2024-01-06",
    },
    {
      id: 7,
      title: "Boi Soberano",
      artist: "Tião Carreiro & Pardinho",
      youtube_url: "https://www.youtube.com/watch?v=pqr678",
      youtube_id: "pqr678",
      thumbnail: "https://img.youtube.com/vi/pqr678/hqdefault.jpg",
      views: 2800000,
      status: "approved",
      formatted_views: "2.8M",
      created_at: "2024-01-07",
    },
    {
      id: 8,
      title: "Festa na Roça",
      artist: "Tião Carreiro & Pardinho",
      youtube_url: "https://www.youtube.com/watch?v=stu901",
      youtube_id: "stu901",
      thumbnail: "https://img.youtube.com/vi/stu901/hqdefault.jpg",
      views: 2500000,
      status: "approved",
      formatted_views: "2.5M",
      created_at: "2024-01-08",
    },
  ],
  current_page: 1,
  last_page: 5,
  per_page: 6,
  total: 25,
  next_page_url: "/songs/remaining?page=2",
  prev_page_url: null,
}
